<?php

use Illuminate\Database\Seeder;

class InscripcionesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('inscripciones')->delete();
        
        \DB::table('inscripciones')->insert(array (
            0 => 
            array (
                'id' => 1,
                'anio' => 2019,
                'numero' => 1,
                'usuario_id' => 5,
                'fecha' => '2019-09-09',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '0',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => NULL,
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '1',
                'evaluacion' => 0,
                'evaluado_por' => 1,
                'comentario_admin' => NULL,
                'created_at' => '2019-09-09 23:55:51',
                'updated_at' => '2019-09-09 23:55:51',
            ),
            1 => 
            array (
                'id' => 2,
                'anio' => 2019,
                'numero' => 2,
                'usuario_id' => 6,
                'fecha' => '2019-09-10',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '85',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => 'Sorteo',
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '5',
                'evaluacion' => 5,
                'evaluado_por' => 3,
                'comentario_admin' => 'Suscripción ganada en sorteo de lanzamiento del ciclo',
                'created_at' => '2019-09-10 12:16:10',
                'updated_at' => '2019-09-10 18:06:05',
            ),
            2 => 
            array (
                'id' => 3,
                'anio' => 2019,
                'numero' => 3,
                'usuario_id' => 7,
                'fecha' => '2019-09-10',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '0',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => NULL,
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '1',
                'evaluacion' => 0,
                'evaluado_por' => 1,
                'comentario_admin' => NULL,
                'created_at' => '2019-09-10 13:38:40',
                'updated_at' => '2019-09-10 13:38:40',
            ),
            3 => 
            array (
                'id' => 4,
                'anio' => 2019,
                'numero' => 4,
                'usuario_id' => 8,
                'fecha' => '2019-09-10',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '85',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => 'Sorteo',
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '5',
                'evaluacion' => 5,
                'evaluado_por' => 3,
                'comentario_admin' => 'Suscripción ganada en sorteo de lanzamiento del ciclo',
                'created_at' => '2019-09-10 18:15:51',
                'updated_at' => '2019-09-10 18:15:52',
            ),
            4 => 
            array (
                'id' => 5,
                'anio' => 2019,
                'numero' => 5,
                'usuario_id' => 10,
                'fecha' => '2019-09-10',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '0',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => NULL,
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '1',
                'evaluacion' => 0,
                'evaluado_por' => 1,
                'comentario_admin' => NULL,
                'created_at' => '2019-09-10 18:29:49',
                'updated_at' => '2019-09-10 18:29:49',
            ),
            5 => 
            array (
                'id' => 6,
                'anio' => 2019,
                'numero' => 6,
                'usuario_id' => 12,
                'fecha' => '2019-09-10',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '0',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => NULL,
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '1',
                'evaluacion' => 0,
                'evaluado_por' => 1,
                'comentario_admin' => NULL,
                'created_at' => '2019-09-10 20:57:45',
                'updated_at' => '2019-09-10 20:57:45',
            ),
            6 => 
            array (
                'id' => 7,
                'anio' => 2019,
                'numero' => 7,
                'usuario_id' => 16,
                'fecha' => '2019-09-11',
                'moneda' => 'S/.',
                'subtotal' => '85',
                'descuento' => '0',
                'notas_cotizacion' => NULL,
                'voucher' => NULL,
                'banco' => 1,
                'observaciones_voucher' => NULL,
                'tipo' => 0,
                'igv' => 18,
                'razon_social' => NULL,
                'ruc' => NULL,
                'domicilio' => NULL,
                'estado' => '1',
                'evaluacion' => 0,
                'evaluado_por' => 1,
                'comentario_admin' => NULL,
                'created_at' => '2019-09-11 19:19:00',
                'updated_at' => '2019-09-11 19:19:00',
            ),
        ));
        
        
    }
}