<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'nombres' => 'Usuario',
                'apellidos' => 'de Soporte',
                'email' => 'super@super.com',
                'password' => '$2y$10$BgIzS3l0ilV4/5wpqurSGexSfoFedNXTgdgcIZwFaEYcmLXyIScTa',
                'telefono' => NULL,
                'tipo' => 1,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'Fnr3nrpzx93Qr4aY6nbUz3RIOQJcbK2ExPCxEuZk5kzFO0Ihcjx9m5Bbe7dW',
                'created_at' => '2019-06-26 01:00:00',
                'updated_at' => '2019-06-26 01:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'nombres' => 'Jesus',
                'apellidos' => 'Cordova Condori',
                'email' => 'admin@tuprofeenlinea.com',
                'password' => '$2y$10$BgIzS3l0ilV4/5wpqurSGexSfoFedNXTgdgcIZwFaEYcmLXyIScTa',
                'telefono' => '',
                'tipo' => 1,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => '3p5yR122p2oS1bQqGzAh8PZHuiQchJmsFDTvYf7d52gRyHkwb3gWvO8R3aSp',
                'created_at' => '2019-06-26 01:00:00',
                'updated_at' => '2019-06-26 01:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'nombres' => 'Walter',
                'apellidos' => 'Calizaya Limache',
                'email' => 'waltercalizaya@hotmail.com',
                'password' => '$2y$10$BgIzS3l0ilV4/5wpqurSGexSfoFedNXTgdgcIZwFaEYcmLXyIScTa',
                'telefono' => '921892150',
                'tipo' => 1,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => '3CDNPsdO25279zLceAO9qPAN07vWmWe0qE4cmRe3Uk9ctjRoeOwKLHBtu3rr',
                'created_at' => '2019-06-26 01:00:00',
                'updated_at' => '2019-06-26 01:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'nombres' => 'Anderson',
                'apellidos' => 'Scala',
                'email' => 'prueba@prueba.com',
                'password' => '$2y$10$BgIzS3l0ilV4/5wpqurSGexSfoFedNXTgdgcIZwFaEYcmLXyIScTa',
                'telefono' => '924656070',
                'tipo' => 2,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'gJCyCeGBDA67mfVhd55x2jOyA1qEMn0fBKrIW8pOhhVnucsMl2iAfAYk3hjj',
                'created_at' => '2019-06-27 23:53:46',
                'updated_at' => '2019-06-27 23:54:48',
            ),
            4 => 
            array (
                'id' => 5,
                'nombres' => 'JC',
                'apellidos' => 'Mora',
                'email' => 'perro_y_o_x@hotmail.com',
                'password' => '$2y$10$mRr0nvwI/fXh5Ov2VAjl8OGULJDGPbUeD1ipacUn.9zrdMk2SVB0y',
                'telefono' => '924656070',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-09 23:53:46',
                'updated_at' => '2019-09-09 23:54:48',
            ),
            5 => 
            array (
                'id' => 6,
                'nombres' => 'salomon',
                'apellidos' => 'percca',
                'email' => 'salomonysusamigas@gmail.com',
                'password' => '$2y$10$u4Sl/a0njnikCeI.H8EVX.fooOmk70qsJg2h0LFeuPrfgyn2FmqTi',
                'telefono' => '950184974',
                'tipo' => 2,
                'foto' => NULL,
                'distrito_id' => 230110,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'v7Gm5Q2LF0poOzbf96gdyqFmtlPPvhKBf3n4eeWvWDyfMAyKcIrwSOdmb0R2',
                'created_at' => '2019-09-10 08:09:58',
                'updated_at' => '2019-09-10 08:11:24',
            ),
            6 => 
            array (
                'id' => 7,
                'nombres' => 'Juan',
                'apellidos' => 'Loza',
                'email' => 'jdiegolozabernabe@gmail.com',
                'password' => '$2y$10$6/nYay008a.8449ibGYbROdb8WC9ctBRtptcfTyiktjdSJZFHFOYe',
                'telefono' => '945539331',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230102,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'zLur9BBtUCCecMC1CxbBAScel3PDnAzoZ4b9KnV6yltON0QjB4g1SthkKwVf',
                'created_at' => '2019-09-10 13:37:29',
                'updated_at' => '2019-09-10 13:38:12',
            ),
            7 => 
            array (
                'id' => 8,
                'nombres' => 'Andrea',
                'apellidos' => 'Velarde',
                'email' => 'Lo4ndre@gmail.com',
                'password' => '$2y$10$rVYz5BQ2004A84J7ksPF4uv95xh2nyqjkROeUBB1FnhsqhztmkP7m',
                'telefono' => '910574936',
                'tipo' => 2,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 's4dbnvLZ1wID0xpbCMkHPilrPbKwZiMGs8vdymdAFEHT1WXhYwO73pKLxpCv',
                'created_at' => '2019-09-10 15:10:59',
                'updated_at' => '2019-09-10 15:12:08',
            ),
            8 => 
            array (
                'id' => 9,
                'nombres' => 'Mauricio',
                'apellidos' => 'Guzman Tinoco',
                'email' => 'maguti_24@hotmail.com',
                'password' => '$2y$10$1rzpAiYavI8HfyH5ItSNTOmLSeyZnPtSWjL9DJ/7TryASQTF2mqkS',
                'telefono' => '92734369',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 150103,
                'confirmado' => 0,
                'confirmacion_code' => 'CsV3toqTdJLi431eLnjPFaWY9',
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'al1E0kwcKpMyv6XY9fpu0JtDqwJCjn8ZaaRThuaPzlKPamylfHsWvYYR3Tos',
                'created_at' => '2019-09-10 16:37:46',
                'updated_at' => '2019-09-10 16:37:46',
            ),
            9 => 
            array (
                'id' => 10,
                'nombres' => 'Luis Angel',
                'apellidos' => 'Condori Muñuico',
                'email' => 'luisx003@gmail.com',
                'password' => '$2y$10$eOdVvUeDYIUbBds/xnxGKe8WWb4PN0uds14jacAvvtV7dXjy0Wm2u',
                'telefono' => '974420211',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230110,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-10 18:27:45',
                'updated_at' => '2019-09-10 18:28:39',
            ),
            10 => 
            array (
                'id' => 11,
                'nombres' => 'Crash',
                'apellidos' => 'Bandicoot',
                'email' => 'crash1940@hotmail.com',
                'password' => '$2y$10$XnCDKgM55fnvpDlmu2zX4OKewaxgfbqUeNwlaeRLYC7ciFjpSrBnm',
                'telefono' => '971044666',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 120201,
                'confirmado' => 0,
                'confirmacion_code' => 'Q36m5nUUevkaPutPsMmD2ITuG',
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-10 19:35:15',
                'updated_at' => '2019-09-10 19:35:15',
            ),
            11 => 
            array (
                'id' => 12,
                'nombres' => 'DIEGO',
                'apellidos' => 'CACHICATARI CALLISAYA',
                'email' => 'lostecladossonmios@outlook.com',
                'password' => '$2y$10$JfShYa4qYAtbEgeTiy4LOu./0fPJxeL7mgWBEfRqK78dm053iV/Di',
                'telefono' => '910850166',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230110,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => '9lAC9ZgnGhAzYwnzuclAxB6Vqs6uRX9AkCvDfQQAzQzHc4QxARj03m3aviUD',
                'created_at' => '2019-09-10 20:43:27',
                'updated_at' => '2019-09-10 20:53:00',
            ),
            12 => 
            array (
                'id' => 13,
                'nombres' => 'julio',
                'apellidos' => 'cesar',
                'email' => 'yulio.fy@hotmail.com',
                'password' => '$2y$10$rn6WKU9xSlb29bQf8eg8yOYO637LmBax/m94BV8KEtBTeKRsJMUNa',
                'telefono' => '956619996',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230101,
                'confirmado' => 0,
                'confirmacion_code' => 'oGONYkcJZFHSmeIFA9AElHEfd',
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'epW3SKpG4WJG3W5c54vp0GoOfhq7lRTnZkmLMmL9eoxmY5DWcqYVBU7Yes9E',
                'created_at' => '2019-09-10 20:52:45',
                'updated_at' => '2019-09-10 20:52:45',
            ),
            13 => 
            array (
                'id' => 14,
                'nombres' => 'Melania',
                'apellidos' => 'Perca',
                'email' => 'melaniapercamasc@hotmail.com',
                'password' => '$2y$10$KQ5/LA3cdd51ukpHx7aOyup7CdeF0mWR1btgKsnjNy0oqF6jqL5OS',
                'telefono' => '984363274',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230102,
                'confirmado' => 0,
                'confirmacion_code' => 'zDim0ncaNMUGf7oSjUpSuaQs3',
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => 'O3wmnbw0t8zmzMDgl321zyVtTfWM3NCTZeAXHe1xks4vDOgBTzAgQBH50tB3',
                'created_at' => '2019-09-10 21:30:32',
                'updated_at' => '2019-09-10 21:30:32',
            ),
            14 => 
            array (
                'id' => 15,
                'nombres' => 'Melania',
                'apellidos' => 'Perca',
                'email' => 'melaniapercamasc@gmail.com',
                'password' => '$2y$10$nERrJ4K2VcvkDekZnvc1OOlhUsyfMROZEWnFR8ugOc6DIsA01kKEu',
                'telefono' => '984363274',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230102,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-10 21:35:38',
                'updated_at' => '2019-09-10 21:37:22',
            ),
            15 => 
            array (
                'id' => 16,
                'nombres' => 'fernando',
                'apellidos' => 'lope ancco',
                'email' => 'iope_ancco@hotmail.com',
                'password' => '$2y$10$QWFjYo8Qx1QcJZoM.n9YO.3FiIfTa0n9zHc64bsnwKsUpy5yD0ygO',
                'telefono' => '952625183',
                'tipo' => 3,
                'foto' => NULL,
                'distrito_id' => 230110,
                'confirmado' => 1,
                'confirmacion_code' => NULL,
                'activo' => 1,
                'banneado' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 18:52:25',
                'updated_at' => '2019-09-11 19:13:17',
            ),
        ));
        
        
    }
}